### ISSUE TITLE
[NSML] 메캅 사용 관련 문의

### ISSUE THREAD

**Issue by nammyoungjin** [hunminjeongeum-competition-final-2021/dialogue-summarization#1]
# 주제
- 메캅 사용을 위한 도커 이미지 사용이 가능할까요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 예선에서 konlpy mecab 사용이 불가능했습니다. 도커 이미지를 직접 업로드하는 것도 안되는 것 같았는데 혹시 mecab사용이 가능하게 준비해주실 수 있을지 여쭙고 싶습니다.

**Comment by DaconHoneyBee** [comment]
@nammyoungjin 안녕하세요.
예선에서 konlpy, mecab 사용 가능했으며(Tokenizer 사용에 제한을 두지 않음), 본선도 같은 규칙을 적용합니다.
**mecab 사용 가능하며, 커스텀 도커 이미지로 사용 가능합니다.**
다만, pre-trained 모델은 사용 불가합니다.
감사합니다.

**Comment by nammyoungjin** [comment]
안녕하세요, 커스텀 도커 이미지 사용 관련 질문이 있습니다.

# nsml: teddylee777/docker-kaggle-ko:latest

Docker 이미지를 실행하니 nsml에 
<img width="512" alt="스크린샷 2021-11-03 오후 4 47 40" src="https://user-images.githubusercontent.com/33752068/140024601-fa5cf492-7802-4cf8-a93f-a705de14c232.png">
다음과 같은 오류가 뜹니다.
혹시 해결방법을 알 수 있을까요?

감사합니다.
