### ISSUE TITLE
[대회 진행 관련 문의] 모델 재현성 평가 관련 질문드립니다

### ISSUE THREAD

**Issue by sohyunwriter** [hunminjeongeum-competition-final-2021/dialogue-summarization#2]
# 주제
- 모델 재현성 평가 관련 질문드립니다

# 상황 (자세히 작성해주시면 좋습니다.)
- pretrained model은 사용불가능하다고 인지하고 있는데요, 이외에 추가적인 모델 제한사항이 있는지 여쭤봅니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- **모델 재현 시 학습시간에 제한이 있나요?** 
- 즉, 예선 때도 모델 재현성 평가가 있는 것처럼 보였는데, 제출한 코드로 최종 모델을 만들기까지 몇 시간 내로 끝나야한다는 제한이 있는지 여쭤봅니다.

# 기타 문의 사항
-

**Comment by DaconHoneyBee** [comment]
@sohyunwriter 안녕하세요.

코드 검증은 최종 리더보드 제출시에 사용된 세션을 NSML로부터 전달받아 규정 위반 여부를 평가하고 있습니다.
실제로 실행 및 제출까지 완료한 세션의 소스 코드를 검토하는 것이기에, 재현성 평가는 자동으로 이루어진다고 볼 수 있습니다.
pre-trained 모델 사용은 금지되어 있으며, 학습 소요 시간에는 제한이 없습니다.

감사합니다.
