### ISSUE TITLE
[Dataset] NSML상 데이터 업데이트

### ISSUE THREAD

**Issue by KHY13** [hunminjeongeum-competition-final-2021/dialogue-summarization#3]
# 주제
- NSML상 데이터 업데이트 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- 안녕하세요 README를 보면 본선은 9개의 주제 모두 사용해서 진행이 되는 것 같은데 NSML상에 데이터는 업데이트가 안되어 예선전과 같은 데이터인 것 같습니다.  확인부탁드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by KHY13** [comment]
final_dialogue 데이터가 따로 있네요 다른 참가자분들도 세션 생성하실때 주의하셔야 할 것 같아요

**Comment by DaconHoneyBee** [comment]
@KHY1 안녕하세요.
예선에 사용된 dataset은 `dialogue`이고, 본선에 사용되는 데이터셋은 `final_dialogue` 입니다.
감사합니다.
