### ISSUE TITLE
[Dataset] 데이터 구조는 예선과 동일할까요?

### ISSUE THREAD

**Issue by KyungHyunLim** [hunminjeongeum-competition-final-2021/dialogue-summarization#5]
# 주제
- 데이터 구조는 예선과 동일할까요?

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by DaconHoneyBee** [comment]
@KyungHyunLim 안녕하세요.
데이터 구조는 예선과 동일합니다.
감사합니다.
