### ISSUE TITLE
[대회 진행 관련 문의]

### ISSUE THREAD

**Issue by bellhyeon** [hunminjeongeum-competition-final-2021/dialogue-summarization#8]
# 주제
- Pretrained Tokenizer 관련 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 본 대회에서 Pretrained Tokenizer의 사용이 허가된것으로 알고있는데, Local에서 별도의Data로 사전훈련된 Vocab File을 NSML상에서 사용해도 되는것인지 궁금합니다. 
또한 nsml run -e main.py시 main.py가 위치한 폴더 내의 모든 파일이 nsml상에 로드되는것처럼 보였는데 이러한 Local의 vocab file을 사용해도 되는것인지 문의드립니다.

# 기타 문의 사항
-

**Comment by DaconHoneyBee** [comment]
@bellhyeon 안녕하세요.
커스텀 Vocab file 사용하셔도 됩니다.
감사합니다.
